// Generated by React Router

import "react-router";

declare module "react-router" {
  interface Register {
    pages: Pages;
    routeFiles: RouteFiles;
    routeModules: RouteModules;
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/agents": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/forgot-password": {
    params: {};
  };
  "/reset-password": {
    params: {};
  };
  "/verify-email": {
    params: {};
  };
  "/buyer-dashboard": {
    params: {};
  };
  "/buyer-dashboard/orders": {
    params: {};
  };
  "/buyer-dashboard/shop": {
    params: {};
  };
  "/buyer-dashboard/wallet": {
    params: {};
  };
  "/buyer-dashboard/checkout": {
    params: {};
  };
  "/buyer-dashboard/notification": {
    params: {};
  };
  "/buyer-dashboard/settings": {
    params: {};
  };
  "/agent-dashboard": {
    params: {};
  };
  "/agent-dashboard/request-stock": {
    params: {};
  };
  "/agent-dashboard/daily-report": {
    params: {};
  };
  "/agent-dashboard/leaderboard": {
    params: {};
  };
  "/agent-dashboard/wallet": {
    params: {};
  };
  "/agent-dashboard/notification": {
    params: {};
  };
  "/agent-dashboard/settings": {
    params: {};
  };
  "/admin-dashboard": {
    params: {};
  };
  "/admin-dashboard/agents": {
    params: {};
  };
  "/admin-dashboard/buyers": {
    params: {};
  };
  "/admin-dashboard/settings": {
    params: {};
  };
  "/admin-dashboard/products": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page:
      | "/"
      | "/contact"
      | "/agents"
      | "/login"
      | "/signup"
      | "/forgot-password"
      | "/reset-password"
      | "/verify-email"
      | "/buyer-dashboard"
      | "/buyer-dashboard/orders"
      | "/buyer-dashboard/shop"
      | "/buyer-dashboard/wallet"
      | "/buyer-dashboard/checkout"
      | "/buyer-dashboard/notification"
      | "/buyer-dashboard/settings"
      | "/agent-dashboard"
      | "/agent-dashboard/request-stock"
      | "/agent-dashboard/daily-report"
      | "/agent-dashboard/leaderboard"
      | "/agent-dashboard/wallet"
      | "/agent-dashboard/notification"
      | "/agent-dashboard/settings"
      | "/admin-dashboard"
      | "/admin-dashboard/agents"
      | "/admin-dashboard/buyers"
      | "/admin-dashboard/settings"
      | "/admin-dashboard/products";
  };
  "routes/landing/layout.tsx": {
    id: "routes/landing/layout";
    page: "/" | "/contact" | "/agents";
  };
  "routes/landing/home.tsx": {
    id: "routes/landing/home";
    page: "/";
  };
  "routes/landing/contact.tsx": {
    id: "routes/landing/contact";
    page: "/contact";
  };
  "routes/landing/agents.tsx": {
    id: "routes/landing/agents";
    page: "/agents";
  };
  "routes/auth/layout.tsx": {
    id: "routes/auth/layout";
    page:
      | "/login"
      | "/signup"
      | "/forgot-password"
      | "/reset-password"
      | "/verify-email";
  };
  "routes/auth/login.tsx": {
    id: "routes/auth/login";
    page: "/login";
  };
  "routes/auth/signup.tsx": {
    id: "routes/auth/signup";
    page: "/signup";
  };
  "routes/auth/forgot-password.tsx": {
    id: "routes/auth/forgot-password";
    page: "/forgot-password";
  };
  "routes/auth/reset-password.tsx": {
    id: "routes/auth/reset-password";
    page: "/reset-password";
  };
  "routes/auth/verify-email.tsx": {
    id: "routes/auth/verify-email";
    page: "/verify-email";
  };
  "routes/dashboards/buyer/layout.tsx": {
    id: "routes/dashboards/buyer/layout";
    page:
      | "/buyer-dashboard"
      | "/buyer-dashboard/orders"
      | "/buyer-dashboard/shop"
      | "/buyer-dashboard/wallet"
      | "/buyer-dashboard/checkout"
      | "/buyer-dashboard/notification"
      | "/buyer-dashboard/settings";
  };
  "routes/dashboards/buyer/overview.tsx": {
    id: "routes/dashboards/buyer/overview";
    page: "/buyer-dashboard";
  };
  "routes/dashboards/buyer/orders.tsx": {
    id: "routes/dashboards/buyer/orders";
    page: "/buyer-dashboard/orders";
  };
  "routes/dashboards/buyer/shop.tsx": {
    id: "routes/dashboards/buyer/shop";
    page: "/buyer-dashboard/shop";
  };
  "routes/dashboards/buyer/wallet.tsx": {
    id: "routes/dashboards/buyer/wallet";
    page: "/buyer-dashboard/wallet";
  };
  "routes/dashboards/buyer/checkout.tsx": {
    id: "routes/dashboards/buyer/checkout";
    page: "/buyer-dashboard/checkout";
  };
  "routes/dashboards/buyer/notification.tsx": {
    id: "routes/dashboards/buyer/notification";
    page: "/buyer-dashboard/notification";
  };
  "routes/dashboards/buyer/settings.tsx": {
    id: "routes/dashboards/buyer/settings";
    page: "/buyer-dashboard/settings";
  };
  "routes/dashboards/agent/layout.tsx": {
    id: "routes/dashboards/agent/layout";
    page:
      | "/agent-dashboard"
      | "/agent-dashboard/request-stock"
      | "/agent-dashboard/daily-report"
      | "/agent-dashboard/leaderboard"
      | "/agent-dashboard/wallet"
      | "/agent-dashboard/notification"
      | "/agent-dashboard/settings";
  };
  "routes/dashboards/agent/overview.tsx": {
    id: "routes/dashboards/agent/overview";
    page: "/agent-dashboard";
  };
  "routes/dashboards/agent/request-stock.tsx": {
    id: "routes/dashboards/agent/request-stock";
    page: "/agent-dashboard/request-stock";
  };
  "routes/dashboards/agent/daily-report.tsx": {
    id: "routes/dashboards/agent/daily-report";
    page: "/agent-dashboard/daily-report";
  };
  "routes/dashboards/agent/leaderboard.tsx": {
    id: "routes/dashboards/agent/leaderboard";
    page: "/agent-dashboard/leaderboard";
  };
  "routes/dashboards/agent/wallet.tsx": {
    id: "routes/dashboards/agent/wallet";
    page: "/agent-dashboard/wallet";
  };
  "routes/dashboards/agent/notification.tsx": {
    id: "routes/dashboards/agent/notification";
    page: "/agent-dashboard/notification";
  };
  "routes/dashboards/agent/settings.tsx": {
    id: "routes/dashboards/agent/settings";
    page: "/agent-dashboard/settings";
  };
  "routes/dashboards/admin/layout.tsx": {
    id: "routes/dashboards/admin/layout";
    page:
      | "/admin-dashboard"
      | "/admin-dashboard/agents"
      | "/admin-dashboard/buyers"
      | "/admin-dashboard/settings"
      | "/admin-dashboard/products";
  };
  "routes/dashboards/admin/overview.tsx": {
    id: "routes/dashboards/admin/overview";
    page: "/admin-dashboard";
  };
  "routes/dashboards/admin/agents.tsx": {
    id: "routes/dashboards/admin/agents";
    page: "/admin-dashboard/agents";
  };
  "routes/dashboards/admin/buyers.tsx": {
    id: "routes/dashboards/admin/buyers";
    page: "/admin-dashboard/buyers";
  };
  "routes/dashboards/admin/settings.tsx": {
    id: "routes/dashboards/admin/settings";
    page: "/admin-dashboard/settings";
  };
  "routes/dashboards/admin/products.tsx": {
    id: "routes/dashboards/admin/products";
    page: "/admin-dashboard/products";
  };
};

type RouteModules = {
  root: typeof import("./app/root.tsx");
  "routes/landing/layout": typeof import("./app/routes/landing/layout.tsx");
  "routes/landing/home": typeof import("./app/routes/landing/home.tsx");
  "routes/landing/contact": typeof import("./app/routes/landing/contact.tsx");
  "routes/landing/agents": typeof import("./app/routes/landing/agents.tsx");
  "routes/auth/layout": typeof import("./app/routes/auth/layout.tsx");
  "routes/auth/login": typeof import("./app/routes/auth/login.tsx");
  "routes/auth/signup": typeof import("./app/routes/auth/signup.tsx");
  "routes/auth/forgot-password": typeof import("./app/routes/auth/forgot-password.tsx");
  "routes/auth/reset-password": typeof import("./app/routes/auth/reset-password.tsx");
  "routes/auth/verify-email": typeof import("./app/routes/auth/verify-email.tsx");
  "routes/dashboards/buyer/layout": typeof import("./app/routes/dashboards/buyer/layout.tsx");
  "routes/dashboards/buyer/overview": typeof import("./app/routes/dashboards/buyer/overview.tsx");
  "routes/dashboards/buyer/orders": typeof import("./app/routes/dashboards/buyer/orders.tsx");
  "routes/dashboards/buyer/shop": typeof import("./app/routes/dashboards/buyer/shop.tsx");
  "routes/dashboards/buyer/wallet": typeof import("./app/routes/dashboards/buyer/wallet.tsx");
  "routes/dashboards/buyer/checkout": typeof import("./app/routes/dashboards/buyer/checkout.tsx");
  "routes/dashboards/buyer/notification": typeof import("./app/routes/dashboards/buyer/notification.tsx");
  "routes/dashboards/buyer/settings": typeof import("./app/routes/dashboards/buyer/settings.tsx");
  "routes/dashboards/agent/layout": typeof import("./app/routes/dashboards/agent/layout.tsx");
  "routes/dashboards/agent/overview": typeof import("./app/routes/dashboards/agent/overview.tsx");
  "routes/dashboards/agent/request-stock": typeof import("./app/routes/dashboards/agent/request-stock.tsx");
  "routes/dashboards/agent/daily-report": typeof import("./app/routes/dashboards/agent/daily-report.tsx");
  "routes/dashboards/agent/leaderboard": typeof import("./app/routes/dashboards/agent/leaderboard.tsx");
  "routes/dashboards/agent/wallet": typeof import("./app/routes/dashboards/agent/wallet.tsx");
  "routes/dashboards/agent/notification": typeof import("./app/routes/dashboards/agent/notification.tsx");
  "routes/dashboards/agent/settings": typeof import("./app/routes/dashboards/agent/settings.tsx");
  "routes/dashboards/admin/layout": typeof import("./app/routes/dashboards/admin/layout.tsx");
  "routes/dashboards/admin/overview": typeof import("./app/routes/dashboards/admin/overview.tsx");
  "routes/dashboards/admin/agents": typeof import("./app/routes/dashboards/admin/agents.tsx");
  "routes/dashboards/admin/buyers": typeof import("./app/routes/dashboards/admin/buyers.tsx");
  "routes/dashboards/admin/settings": typeof import("./app/routes/dashboards/admin/settings.tsx");
  "routes/dashboards/admin/products": typeof import("./app/routes/dashboards/admin/products.tsx");
};
